version: '3'
services:
  web:
    build: 
      context: ./build
      args:
        - USER_ID=1000
        - PHP_VERSION=7.2
        - WEBROOT=/webroot
    volumes:
      - ./webroot:/webroot:cached
      - ~/.composer-docker:/var/www/.composer
    ports:
      - 8080:80
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001
    depends_on: 
      - db
    networks:
      - docker-bridge
  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
    networks:
      - docker-bridge
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    depends_on: 
      - db
    networks:
      - docker-bridge
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
    networks:
      - docker-bridge
volumes:
  db-data:
networks:
    docker-bridge:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: docker-bridge
