version: '3'
services:
  web:
    build: 
      context: ./build
      args:
        - USER_ID=1000
        - PHP_VERSION=7.2
        - WEBROOT=/webroot
    volumes:
      - ./webroot:/webroot:cached
      - ~/.composer-docker:/var/www/.composer
    ports:
      - 8080:80
    depends_on: 
      - db
  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    depends_on: 
      - db
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
volumes:
  db-data: